2015-12-15 13:29:07 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Admin could not be found.
Exception Attributes: array (
  'class' => 'Admin',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /s_n_clone/social_networking/admin
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-15 13:29:17 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::admin() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'admin',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /s_n_clone/social_networking/users/admin
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\s_n_clone\social_networking\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-12-15 13:29:27 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Admin could not be found.
Exception Attributes: array (
  'class' => 'Admin',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /s_n_clone/social_networking/admin/users
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2015-12-15 14:07:45 Warning: Warning (4096): Argument 1 passed to App\Controller\UsersController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Event\EventManager.php on line 385 and defined in [C:\xampp\htdocs\s_n_clone\social_networking\src\Controller\UsersController.php, line 15]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 140
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 15
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-15 14:07:45 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\s_n_clone\social_networking\src\Controller\UsersController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 209
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 92
[main] - [internal], line ??



2015-12-15 14:07:46 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /s_n_clone/social_networking/users/add
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(92): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-15 14:08:22 Warning: Warning (4096): Argument 1 passed to App\Controller\UsersController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Event\EventManager.php on line 385 and defined in [C:\xampp\htdocs\s_n_clone\social_networking\src\Controller\UsersController.php, line 15]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 140
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 15
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-15 14:09:39 Warning: Warning (4096): Argument 1 passed to App\Controller\UsersController::beforeFilter() must be an instance of App\Controller\Event, instance of Cake\Event\Event given, called in C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Event\EventManager.php on line 385 and defined in [C:\xampp\htdocs\s_n_clone\social_networking\src\Controller\UsersController.php, line 15]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 140
App\Controller\UsersController::beforeFilter() - APP/Controller\UsersController.php, line 15
Cake\Event\EventManager::_callListener() - CORE\src\Event\EventManager.php, line 385
Cake\Event\EventManager::dispatch() - CORE\src\Event\EventManager.php, line 355
Cake\Controller\Controller::dispatchEvent() - CORE\src\Event\EventDispatcherTrait.php, line 78
Cake\Controller\Controller::startupProcess() - CORE\src\Controller\Controller.php, line 491
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 109
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 37



2015-12-15 14:09:39 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\s_n_clone\social_networking\src\Controller\UsersController.php, line 18]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 209
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 92
[main] - [internal], line ??



2015-12-15 14:09:39 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /s_n_clone/social_networking/users/add
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(92): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 18)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-15 14:10:30 Error: Fatal Error (1): Call to a member function allow() on boolean in [C:\xampp\htdocs\s_n_clone\social_networking\src\Controller\UsersController.php, line 19]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 209
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 92
[main] - [internal], line ??



2015-12-15 14:10:31 Error: [Cake\Error\FatalErrorException] Call to a member function allow() on boolean
Request URL: /s_n_clone/social_networking/users/add
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(92): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 19)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-15 14:21:38 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /s_n_clone/social_networking/users/login
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\s_n_clone\social_networking\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-12-15 14:22:58 Error: [Cake\Controller\Exception\MissingActionException] Action UsersController::login() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'UsersController',
  'action' => 'login',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /s_n_clone/social_networking/users/login
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#2 C:\xampp\htdocs\s_n_clone\social_networking\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2015-12-15 14:24:12 Error: [Cake\View\Exception\MissingTemplateException] Template file "Users\login.ctp" is missing.
Exception Attributes: array (
  'file' => 'Users\\login.ctp',
)
Request URL: /s_n_clone/social_networking/users/login
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\View\View.php(576): Cake\View\View->_getViewFileName(NULL)
#1 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#2 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#4 C:\xampp\htdocs\s_n_clone\social_networking\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2015-12-15 15:15:21 Error: Fatal Error (4): syntax error, unexpected 'echo' (T_ECHO) in [C:\xampp\htdocs\s_n_clone\social_networking\src\Template\Layout\default.ctp, line 40]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 209
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 92
[main] - [internal], line ??



2015-12-15 15:15:22 Error: [Cake\Error\FatalErrorException] syntax error, unexpected 'echo' (T_ECHO)
Request URL: /s_n_clone/social_networking/users/login
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(92): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 40)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-15 15:23:43 Error: [Cake\View\Exception\MissingHelperException] Helper class AuthHelper could not be found.
Exception Attributes: array (
  'class' => 'AuthHelper',
  'plugin' => NULL,
)
Request URL: /s_n_clone/social_networking/users/login
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\View\HelperRegistry->_throwMissingClassError('Auth', NULL)
#1 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\View\HelperRegistry.php(66): Cake\Core\ObjectRegistry->load('Auth')
#2 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\View\View.php(867): Cake\View\HelperRegistry->__isset('Auth')
#3 C:\xampp\htdocs\s_n_clone\social_networking\src\Template\Layout\default.ctp(45): Cake\View\View->__get('Auth')
#4 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\View\View.php(971): include('C:\\xampp\\htdocs...')
#5 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\View\View.php(931): Cake\View\View->_evaluate('C:\\xampp\\htdocs...', Array)
#6 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\View\View.php(625): Cake\View\View->_render('C:\\xampp\\htdocs...')
#7 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\View\View.php(584): Cake\View\View->renderLayout('', 'default')
#8 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Controller\Controller.php(611): Cake\View\View->render(NULL, NULL)
#9 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#10 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\UsersController))
#11 C:\xampp\htdocs\s_n_clone\social_networking\webroot\index.php(37): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#12 {main}


2015-12-15 15:28:52 Error: Fatal Error (1): Call to a member function check() on null in [C:\xampp\htdocs\s_n_clone\social_networking\src\Template\Layout\default.ctp, line 45]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 209
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 92
[main] - [internal], line ??



2015-12-15 15:28:52 Error: [Cake\Error\FatalErrorException] Call to a member function check() on null
Request URL: /s_n_clone/social_networking/users/login
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(92): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Call to a membe...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2015-12-15 15:34:33 Error: Fatal Error (4): syntax error, unexpected '}', expecting ',' or ';' in [C:\xampp\htdocs\s_n_clone\social_networking\src\Template\Layout\default.ctp, line 45]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 209
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 92
[main] - [internal], line ??



2015-12-15 15:34:34 Error: [Cake\Error\FatalErrorException] syntax error, unexpected '}', expecting ',' or ';'
Request URL: /s_n_clone/social_networking/users/login
Stack Trace:
#0 C:\xampp\htdocs\s_n_clone\social_networking\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(92): Cake\Error\BaseErrorHandler->handleFatalError(4, 'syntax error, u...', 'C:\\xampp\\htdocs...', 45)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


